version: 2
sources:
  - name: sneha
    description: Sneha Superset metadata
    schema: sneha
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: atcef
    description: Atcef Superset metadata
    schema: atcef
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: noora_health
    description: Noora Health Superset metadata
    schema: noora_health
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: akrsp
    description: AKRSP (arghyam) Superset metadata
    schema: akrsp
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
      tests:
      - elementary.schema_changes:
          config:
            severity: warn
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: stir
    description: Stir Superset metadata
    schema: stir
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: shofco
    description: Shofco Superset metadata
    schema: shofco
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: inrem
    description: Inrem Superset metadata
    schema: inrem
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: ummeed
    description: Ummeed Superset metadata
    schema: ummeed
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: cmhlp
    description: CMHLP Superset metadata
    schema: cmhlp
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: tech4dev
    description: Tech4Dev Superset metadata
    schema: tech4dev
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
  - name: goonj
    description: Goonj Superset metadata
    schema: goonj
    tables:
    - name: logs
      identifier: logs
      description: This contains the data of logs and actions
    - name: users
      identifier: ab_user
      description: This table contains details of the superset users
    - name: dashboards
      identifier: dashboards
      description: This table contains details of the dashboards createds
    - name: user_roles
      identifier: ab_user_role
      description: This table contains mapping of users and roles
    - name: roles
      identifier: ab_role
      description: This table contains list of all roles
    - name: slices
      identifier: slices
      description: This table contains data of all charts
    - name: dashboard_roles
      identifier: dashboard_roles
      description: This table contains mapping roles attached to a dashboard
