version: 2

sources:
    - name: sneha
      description: Superset metadata
      schema: sneha
      tables:
          - name: logs
            identifier: logs
            description: This contains the data of logs and actions
          - name: users
            identifier: ab_user
            description: This table contains details of the superset users
          - name: dashboards
            identifier: dashboards
            description: This table contains details of the dashboards createds
          - name: user_roles
            identifier: ab_user_role
            description: This table contains mapping of users and roles
          - name: roles
            identifier: ab_role
            description: This table contains list of all roles
          - name: slices
            identifier: slices
            description: This table contains data of all charts
          - name: dashboard_roles
            identifier: dashboard_roles
            description: This table contains mapping roles attached to a dashboard
    - name: tech4dev
      description: Superset metadata
      schema: tech4dev
      tables:
          - name: logs
            identifier: logs
            description: This contains the data of logs and actions
          - name: users
            identifier: ab_user
            description: This table contains details of the superset users
          - name: dashboards
            identifier: dashboards
            description: This table contains details of the dashboards createds
          - name: user_roles
            identifier: ab_user_role
            description: This table contains mapping of users and roles
          - name: roles
            identifier: ab_role
            description: This table contains list of all roles
          - name: slices
            identifier: slices
            description: This table contains data of all charts
          - name: dashboard_roles
            identifier: dashboard_roles
            description: This table contains mapping roles attached to a dashboard
